site_name: Lost neuroscientist

nav:
  - Home: index.md
  - Data Quality Assurances:
    - data_qc.md
  - DWI workflow:
    - 'Overview': 'overview1.md'
    - 'Estimating data quality': 'eddyqc.md'
    - 'Preprocessing (MRtrix)': 'preproc_mrtrix.md'
    - 'Tractography (MRtrix)': 'mrtrix.md'
    - 'Bundle segmentation (TractSeg)': 'tractseg.md'
    - 'Visualization of bundles': 'bundlevis.md'
  - Visualization: 
    - visualization.md


theme: readthedocs
  features:
    - content.code.copy
    - content.code.select


markdown_extensions:
  - codehilite
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocs-jupyter
  - mknotebooks
  - termynal

